import { describe, expect, it } from 'vitest';
import { renderRegistrySource, sortedIds } from './manifest.js';
import type { TestIdManifest } from './manifest.js';

const manifest: TestIdManifest = {
  algorithmVersion: 1,
  entries: [
    { id: 'checkout-email-input', file: 'src/checkout/CheckoutForm.tsx', component: 'CheckoutForm' },
    { id: 'checkout-submit-button', file: 'src/checkout/CheckoutForm.tsx', component: 'CheckoutForm' },
    { id: 'checkout-email-input', file: 'src/auth/SignupForm.tsx', component: 'SignupForm' },
  ],
};

describe('renderRegistrySource', () => {
  it('emits a const map + TestId union + tid helper, deduplicating ids', () => {
    const src = renderRegistrySource(manifest);
    expect(src).toContain('export const testIds = {');
    expect(src).toContain('"checkout-email-input": "checkout-email-input"');
    expect(src.match(/checkout-email-input/g)?.length).toBe(2); // once as key+value pair, no dup entry
    expect(src).toContain('export type TestId = keyof typeof testIds;');
    expect(src).toContain('export function tid(id: TestId): string {');
    expect(src).toContain('GENERATED by @testable-ui/core');
  });

  it('rendered module is valid TS that self-compiles', () => {
    const src = renderRegistrySource(manifest);
    expect(src).toMatch(/^\s*"checkout-email-input":/m);
  });
});

describe('sortedIds', () => {
  it('dedupes and sorts stably for CI diffing', () => {
    expect(sortedIds(manifest)).toEqual(['checkout-email-input', 'checkout-submit-button']);
  });
});