/**
 * Typed registry emission.
 *
 * The adapter pipeline collects every generated id across the build and
 * renders a small TypeScript module consumers import from test files:
 *
 *   export const testIds = { "checkout-email-input-HASH": "checkout-email-input-HASH" } as const;
 *   export type TestId = keyof typeof testIds;
 *   export function tid(id: TestId): string { return testIds[id]; }
 *
 * `tid()` gives tests autocomplete + a compile error the moment an id is
 * renamed or removed at the source, and masks the path-hash suffix so test
 * code stays readable. The rendering is pure (string -> string) so adapters
 * may write it to disk or serve it as a virtual module.
 */

export interface TestIdEntry {
  id: string;
  /** Module specifier the element was authored in, e.g. `src/checkout/CheckoutForm.tsx`. */
  file: string;
  component: string;
}

export interface TestIdManifest {
  algorithmVersion: number;
  entries: TestIdEntry[];
}

const HEADER =
  '// GENERATED by @testable-ui/core. Do not edit manually — rerun the build.\n';

/** Render `test-ids.ts` (and its content doubles as the .d.ts). */
export function renderRegistrySource(manifest: TestIdManifest): string {
  const ids = manifest.entries.map((e) => e.id).filter((id, i, all) => all.indexOf(id) === i);
  const lines = ids.map((id) => `  ${JSON.stringify(id)}: ${JSON.stringify(id)},`);
  return [
    HEADER,
    `export const testIds = {`,
    ...lines,
    `} as const;`,
    ``,
    `export type TestId = keyof typeof testIds;`,
    ``,
    `export function tid(id: TestId): string {`,
    `  return testIds[id];`,
    `}`,
    ``,
  ].join('\n');
}

/** Build a deduplicated, sorted id list from a manifest (stable CI diffing). */
export function sortedIds(manifest: TestIdManifest): string[] {
  return [...new Set(manifest.entries.map((e) => e.id))].sort();
}